# Generated by Django 3.0.3 on 2020-03-15 17:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('College_Predictor', '0002_auto_20200306_1755'),
    ]

    operations = [
        migrations.AddField(
            model_name='college',
            name='about',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
